server:
  port: 0  # Allows services to run on random ports

spring:
  application:
    name: default-application  # Default name for services without a specific config

logging:
  level:
    root: INFO
