spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    # Do not register this application with Eureka, as it is acting as a standalone Eureka server.
    register-with-eureka: false
    # Do not fetch the registry from another Eureka server, since this is the main registry.
    fetch-registry: false
