spring:
  application:
    name: order-service

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server that this service will register with

logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.openfeign: DEBUG

